// frontend/erp/src/views/inventory/ItemDetail.vue
<!-- src/views/inventory/ItemDetail.vue -->
<template>
  <div class="item-detail-view">
    <div class="page-header">
      <div class="header-left">
        <button class="back-button" @click="$router.back()">
          <i class="fas fa-arrow-left"></i> Back
        </button>
        <h1 class="page-title">Item Details</h1>
      </div>
      
      <div class="header-actions">
        <button class="btn btn-secondary" @click="openEditModal">
          <i class="fas fa-edit"></i> Edit
        </button>
        <button class="btn btn-danger" @click="confirmDelete" v-if="canDelete">
          <i class="fas fa-trash"></i> Delete
        </button>
      </div>
    </div>

    <div v-if="isLoading" class="loading-indicator">
      <i class="fas fa-spinner fa-spin"></i> Loading item details...
    </div>

    <div v-else-if="!item" class="error-message">
      <div class="error-icon">
        <i class="fas fa-exclamation-circle"></i>
      </div>
      <h2>Item Not Found</h2>
      <p>The requested item could not be found.</p>
      <button class="btn btn-primary" @click="$router.push('/items')">
        Back to Items List
      </button>
    </div>

    <div v-else class="item-detail-container">
      <!-- Basic Info Card -->
      <div class="detail-card">
        <div class="card-header">
          <h2 class="card-title">Basic Information</h2>
        </div>
        <div class="card-body">
          <div class="detail-grid">
            <div class="detail-row">
              <div class="detail-label">Item Code</div>
              <div class="detail-value">{{ item.item_code }}</div>
            </div>
            <div class="detail-row">
              <div class="detail-label">Name</div>
              <div class="detail-value">{{ item.name }}</div>
            </div>
            <div class="detail-row">
              <div class="detail-label">Category</div>
              <div class="detail-value">{{ item.category ? item.category.name : '-' }}</div>
            </div>
            <div class="detail-row">
              <div class="detail-label">Unit of Measure</div>
              <div class="detail-value">
                {{ item.unitOfMeasure ? `${item.unitOfMeasure.name} (${item.unitOfMeasure.symbol})` : '-' }}
              </div>
            </div>
            <div class="detail-row" v-if="item.description">
              <div class="detail-label">Description</div>
              <div class="detail-value description">{{ item.description }}</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Stock Info Card -->
      <div class="detail-card">
        <div class="card-header">
          <h2 class="card-title">Stock Information</h2>
        </div>
        <div class="card-body">
          <div class="stock-summary">
            <div class="stock-stat">
              <div class="stat-label">Current Stock</div>
              <div class="stat-value">{{ item.current_stock }}</div>
              <div class="stat-unit">{{ item.unitOfMeasure?.symbol || '' }}</div>
            </div>
            <div class="stock-stat">
              <div class="stat-label">Minimum Stock</div>
              <div class="stat-value">{{ item.minimum_stock }}</div>
              <div class="stat-unit">{{ item.unitOfMeasure?.symbol || '' }}</div>
            </div>
            <div class="stock-stat">
              <div class="stat-label">Maximum Stock</div>
              <div class="stat-value">{{ item.maximum_stock }}</div>
              <div class="stat-unit">{{ item.unitOfMeasure?.symbol || '' }}</div>
            </div>
            <div class="stock-stat">
              <div class="stat-label">Status</div>
              <div class="stat-value status">
                <span class="stock-status" :class="getStockStatusClass(item)">
                  {{ getStockStatus(item) }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Batches Card -->
      <div class="detail-card" v-if="item.batches && item.batches.length > 0">
        <div class="card-header">
          <h2 class="card-title">Batches</h2>
        </div>
        <div class="card-body">
          <div class="card-table">
            <table>
              <thead>
                <tr>
                  <th>Batch Number</th>
                  <th>Expiry Date</th>
                  <th>Manufacturing Date</th>
                  <th>Lot Number</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="batch in item.batches" :key="batch.batch_id">
                  <td>{{ batch.batch_number }}</td>
                  <td>{{ formatDate(batch.expiry_date) }}</td>
                  <td>{{ formatDate(batch.manufacturing_date) }}</td>
                  <td>{{ batch.lot_number || '-' }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Transactions Card -->
      <div class="detail-card">
        <div class="card-header">
          <h2 class="card-title">Recent Transactions</h2>
          <router-link :to="`/stock-transactions?item_id=${item.item_id}`" class="card-action">
            View All
          </router-link>
        </div>
        <div class="card-body">
          <div v-if="isLoadingTransactions" class="loading-indicator">
            <i class="fas fa-spinner fa-spin"></i> Loading transactions...
          </div>
          <div v-else-if="transactions.length === 0" class="empty-state">
            <p>No transactions found for this item.</p>
          </div>
          <div v-else class="card-table">
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Type</th>
                  <th>Quantity</th>
                  <th>Warehouse</th>
                  <th>Reference</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="transaction in transactions" :key="transaction.transaction_id">
                  <td>{{ formatDate(transaction.transaction_date) }}</td>
                  <td>
                    <span class="transaction-type" :class="getTransactionTypeClass(transaction.transaction_type)">
                      {{ transaction.transaction_type }}
                    </span>
                  </td>
                  <td :class="getQuantityClass(transaction.transaction_type)">
                    {{ transaction.quantity }} {{ item.unitOfMeasure?.symbol || '' }}
                  </td>
                  <td>{{ transaction.warehouse?.name || '-' }}</td>
                  <td>{{ transaction.reference_document || '-' }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Item Form Modal -->
    <ItemFormModal
      v-if="showEditModal"
      :is-edit-mode="true"
      :item-form="itemForm"
      :categories="categories"
      :unit-of-measures="unitOfMeasures"
      @save="saveItem"
      @close="closeEditModal"
    />

    <!-- Delete Confirmation Modal -->
    <ConfirmationModal
      v-if="showDeleteModal"
      title="Confirm Delete"
      :message="`Are you sure you want to delete <strong>${item?.name}</strong>?`"
      confirm-button-text="Delete Item"
      confirm-button-class="btn btn-danger"
      @confirm="deleteItem"
      @close="closeDeleteModal"
    />
  </div>
</template>

<script>
import { ref, reactive, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import ItemService from '@/services/ItemService.js';
import ItemFormModal from '@/components/inventory/ItemFormModal.vue';
import ConfirmationModal from '@/components/common/ConfirmationModal.vue';

export default {
  name: 'ItemDetail',
  components: {
    ItemFormModal,
    ConfirmationModal
  },
  props: {
    id: {
      type: [String, Number],
      required: true
    }
  },
  setup(props) {
    const router = useRouter();
    const item = ref(null);
    const transactions = ref([]);
    const categories = ref([]);
    const unitOfMeasures = ref([]);
    const isLoading = ref(true);
    const isLoadingTransactions = ref(true);
    const showEditModal = ref(false);
    const showDeleteModal = ref(false);
    const itemForm = reactive({
      item_id: null,
      item_code: '',
      name: '',
      description: '',
      category_id: '',
      uom_id: '',
      minimum_stock: 0,
      maximum_stock: 0
    });

    const canDelete = computed(() => {
      if (!item.value) return false;
      
      // Check if item has transactions or batches
      const hasTransactions = transactions.value.length > 0;
      const hasBatches = item.value.batches && item.value.batches.length > 0;
      
      return !hasTransactions && !hasBatches;
    });

    const fetchItem = async () => {
      isLoading.value = true;
      try {
        const response = await ItemService.getItemById(props.id);
        item.value = response.data;
        
        // Populate form for potential edit
        Object.assign(itemForm, {
          item_id: item.value.item_id,
          item_code: item.value.item_code,
          name: item.value.name,
          description: item.value.description || '',
          category_id: item.value.category_id || '',
          uom_id: item.value.uom_id || '',
          minimum_stock: item.value.minimum_stock,
          maximum_stock: item.value.maximum_stock
        });
      } catch (error) {
        console.error('Error fetching item:', error);
        item.value = null;
      } finally {
        isLoading.value = false;
      }
    };

    const fetchTransactions = async () => {
      if (!props.id) return;
      
      isLoadingTransactions.value = true;
      try {
        const response = await ItemService.getItemTransactions(props.id, { limit: 10 });
        transactions.value = response.data || [];
      } catch (error) {
        console.error('Error fetching transactions:', error);
        transactions.value = [];
      } finally {
        isLoadingTransactions.value = false;
      }
    };

    const fetchCategories = async () => {
      try {
        const response = await ItemService.getCategories();
        categories.value = response.data || [];
      } catch (error) {
        console.error('Error fetching categories:', error);
        categories.value = [];
      }
    };

    const fetchUnitOfMeasures = async () => {
      try {
        const response = await ItemService.getUnitsOfMeasure();
        unitOfMeasures.value = response.data || [];
      } catch (error) {
        console.error('Error fetching units of measure:', error);
        unitOfMeasures.value = [];
      }
    };

    const formatDate = (dateString) => {
      if (!dateString) return '-';
      const date = new Date(dateString);
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      });
    };

    const getStockStatus = (item) => {
      if (item.current_stock <= item.minimum_stock) {
        return 'Low Stock';
      } else if (item.current_stock >= item.maximum_stock) {
        return 'Over Stock';
      } else {
        return 'Normal';
      }
    };

    const getStockStatusClass = (item) => {
      const status = getStockStatus(item);
      switch (status) {
        case 'Low Stock': return 'low';
        case 'Over Stock': return 'over';
        default: return 'normal';
      }
    };

    const getTransactionTypeClass = (type) => {
      if (['IN', 'RECEIPT', 'RETURN', 'ADJUSTMENT_IN'].includes(type)) {
        return 'type-in';
      } else if (['OUT', 'ISSUE', 'SALE', 'ADJUSTMENT_OUT'].includes(type)) {
        return 'type-out';
      }
      return '';
    };

    const getQuantityClass = (type) => {
      if (['IN', 'RECEIPT', 'RETURN', 'ADJUSTMENT_IN'].includes(type)) {
        return 'quantity-in';
      } else if (['OUT', 'ISSUE', 'SALE', 'ADJUSTMENT_OUT'].includes(type)) {
        return 'quantity-out';
      }
      return '';
    };

    const openEditModal = () => {
      showEditModal.value = true;
    };

    const closeEditModal = () => {
      showEditModal.value = false;
    };

    const saveItem = async (formData) => {
      try {
        await ItemService.updateItem(formData.item_id, formData);
        
        // Refresh item data
        await fetchItem();
        
        // Close modal
        closeEditModal();
        
        // Show success message
        alert('Item updated successfully!');
      } catch (error) {
        console.error('Error updating item:', error);
        
        if (error.validationErrors) {
          alert('Please check the form for errors: ' + Object.values(error.validationErrors).join(', '));
        } else {
          alert('An error occurred while updating the item. Please try again.');
        }
      }
    };

    const confirmDelete = () => {
      showDeleteModal.value = true;
    };

    const closeDeleteModal = () => {
      showDeleteModal.value = false;
    };

    const deleteItem = async () => {
      try {
        await ItemService.deleteItem(props.id);
        
        // Close modal
        closeDeleteModal();
        
        // Show success message
        alert('Item deleted successfully!');
        
        // Navigate back to items list
        router.push('/items');
      } catch (error) {
        console.error('Error deleting item:', error);
        
        if (error.response && error.response.status === 422) {
          alert('This item cannot be deleted because it has related transactions or batches.');
        } else {
          alert('An error occurred while deleting the item. Please try again.');
        }
      }
    };

    onMounted(() => {
      fetchItem();
      fetchTransactions();
      fetchCategories();
      fetchUnitOfMeasures();
    });

    return {
      item,
      transactions,
      categories,
      unitOfMeasures,
      isLoading,
      isLoadingTransactions,
      showEditModal,
      showDeleteModal,
      itemForm,
      canDelete,
      formatDate,
      getStockStatus,
      getStockStatusClass,
      getTransactionTypeClass,
      getQuantityClass,
      openEditModal,
      closeEditModal,
      saveItem,
      confirmDelete,
      closeDeleteModal,
      deleteItem
    };
  }
};
</script>

<style scoped>
.item-detail-view {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.back-button {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  color: #64748b;
  background: none;
  border: none;
  padding: 0.5rem;
  cursor: pointer;
  font-size: 0.875rem;
  transition: color 0.2s;
}

.back-button:hover {
  color: #1e293b;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 600;
  margin: 0;
  color: #1e293b;
}

.header-actions {
  display: flex;
  gap: 0.75rem;
}

.item-detail-container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 1.5rem;
}

.detail-card {
  background-color: white;
  border-radius: 0.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 1.5rem;
  background-color: #f8fafc;
  border-bottom: 1px solid #e2e8f0;
}

.card-title {
  font-size: 1.125rem;
  font-weight: 600;
  margin: 0;
  color: #1e293b;
}

.card-action {
  font-size: 0.875rem;
  color: #2563eb;
  text-decoration: none;
}

.card-action:hover {
  text-decoration: underline;
}

.card-body {
  padding: 1.5rem;
}

.detail-grid {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.detail-row {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.detail-label {
  font-size: 0.75rem;
  color: #64748b;
  font-weight: 500;
}

.detail-value {
  color: #1e293b;
  font-size: 0.875rem;
}

.detail-value.description {
  white-space: pre-line;
  line-height: 1.5;
}

.stock-summary {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  gap: 1rem;
}

.stock-stat {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 1rem;
  border-radius: 0.375rem;
  background-color: #f8fafc;
}

.stat-label {
  font-size: 0.75rem;
  color: #64748b;
  margin-bottom: 0.5rem;
}

.stat-value {
  font-size: 1.5rem;
  font-weight: 600;
  color: #1e293b;
}

.stat-unit {
  font-size: 0.75rem;
  color: #64748b;
  margin-top: 0.25rem;
}

.stat-value.status {
  font-size: 1rem;
}

.stock-status {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.75rem;
  font-weight: 500;
}

.stock-status.low {
  background-color: #fee2e2;
  color: #dc2626;
}

.stock-status.normal {
  background-color: #d1fae5;
  color: #059669;
}

.stock-status.over {
  background-color: #fef3c7;
  color: #d97706;
}

.card-table {
  overflow-x: auto;
}

.card-table table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}

.card-table th {
  text-align: left;
  padding: 0.75rem 0.5rem;
  border-bottom: 1px solid #e2e8f0;
  font-weight: 500;
  color: #64748b;
}

.card-table td {
  padding: 0.75rem 0.5rem;
  border-bottom: 1px solid #f1f5f9;
  color: #1e293b;
}

.transaction-type {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.75rem;
  font-weight: 500;
}

.type-in {
  background-color: #d1fae5;
  color: #059669;
}

.type-out {
  background-color: #fee2e2;
  color: #dc2626;
}

.quantity-in {
  color: #059669;
}

.quantity-out {
  color: #dc2626;
}

.empty-state {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 2rem 0;
  color: #64748b;
  font-style: italic;
}

.loading-indicator {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 2rem 0;
  color: #64748b;
}

.loading-indicator i {
  margin-right: 0.5rem;
}

.error-message {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 4rem 0;
}

.error-icon {
  font-size: 3rem;
  color: #f43f5e;
  margin-bottom: 1rem;
}

.error-message h2 {
  margin: 0 0 0.5rem 0;
  color: #1e293b;
}

.error-message p {
  margin: 0 0 1.5rem 0;
  color: #64748b;
}

@media (max-width: 768px) {
  .item-detail-container {
    grid-template-columns: 1fr;
  }
  
  .page-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }
  
  .header-actions {
    align-self: flex-end;
  }
  
  .stock-summary {
    grid-template-columns: repeat(2, 1fr);
  }
}
</style>

// frontend/src/pages/inventory/items/ItemDetail.jsx
// src/pages/inventory/items/ItemDetail.jsx
import React, { useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import { 
  Edit, 
  Trash, 
  Package, 
  Tag, 
  Ruler, 
  AlertTriangle, 
  Check, 
  Clock, 
  List, 
  TrendingUp, 
  TrendingDown 
} from 'lucide-react';
import { itemService, stockTransactionService } from '../../../services/inventoryService';
import PageHeader from '../../../components/common/PageHeader';
import { Card, CardHeader, CardBody } from '../../../components/common/Card';
import { Button } from '../../../components/common/FormElements';
import Table from '../../../components/common/Table';
import Alert from '../../../components/common/Alert';
import Modal from '../../../components/common/Modal';

const ItemDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  
  // State for delete modal
  const [deleteModalOpen, setDeleteModalOpen] = useState(false);
  
  // Fetch item data
  const { 
    data: itemData, 
    isLoading: itemLoading, 
    isError: itemError 
  } = useQuery(
    ['item', id],
    () => itemService.getById(id)
  );
  
  // Fetch item transactions
  const { 
    data: transactionsData, 
    isLoading: transactionsLoading 
  } = useQuery(
    ['itemTransactions', id],
    () => stockTransactionService.getItemTransactions(id)
  );
  
  // Delete item mutation
  const deleteMutation = useMutation(
    () => itemService.delete(id),
    {
      onSuccess: () => {
        queryClient.invalidateQueries('items');
        navigate('/inventory/items');
      }
    }
  );
  
  // Handle delete item
  const handleDeleteItem = () => {
    deleteMutation.mutate();
  };
  
  const item = itemData?.data;
  const transactions = transactionsData?.data || [];
  
  // Determine stock status for styling
  const getStockStatusInfo = () => {
    if (!item) return { color: 'gray', icon: Clock, text: 'Loading...' };
    
    if (item.current_stock <= 0) {
      return { color: 'red', icon: AlertTriangle, text: 'Out of Stock' };
    }
    
    if (item.current_stock <= item.minimum_stock) {
      return { color: 'orange', icon: AlertTriangle, text: 'Low Stock' };
    }
    
    if (item.current_stock >= item.maximum_stock) {
      return { color: 'yellow', icon: AlertTriangle, text: 'Over Stock' };
    }
    
    return { color: 'green', icon: Check, text: 'In Stock' };
  };
  
  const stockStatus = getStockStatusInfo();
  
  // Transaction table columns
  const transactionColumns = [
    {
      key: 'date',
      label: 'Date',
      render: (transaction) => (
        <div className="text-sm text-gray-900">
          {new Date(transaction.transaction_date).toLocaleDateString()}
        </div>
      )
    },
    {
      key: 'type',
      label: 'Type',
      render: (transaction) => {
        const isInflow = ['IN', 'RECEIPT', 'ADJUSTMENT_IN'].includes(transaction.transaction_type);
        return (
          <span 
            className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${
              isInflow ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
            }`}
          >
            {isInflow ? (
              <TrendingUp className="h-4 w-4 mr-1" />
            ) : (
              <TrendingDown className="h-4 w-4 mr-1" />
            )}
            {transaction.transaction_type}
          </span>
        );
      }
    },
    {
      key: 'quantity',
      label: 'Quantity',
      render: (transaction) => (
        <div className="text-sm text-gray-900">
          {transaction.quantity} {item?.unitOfMeasure?.symbol || ''}
        </div>
      )
    },
    {
      key: 'warehouse',
      label: 'Warehouse',
      render: (transaction) => (
        <div className="text-sm text-gray-900">
          {transaction.warehouse?.name || '-'}
        </div>
      )
    },
    {
      key: 'reference',
      label: 'Reference',
      render: (transaction) => (
        <div className="text-sm text-gray-900">
          {transaction.reference_document && transaction.reference_number ? 
            `${transaction.reference_document} #${transaction.reference_number}` : 
            '-'}
        </div>
      )
    }
  ];
  
  if (itemError) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Alert
          type="error"
          title="Error Loading Item"
          message="Failed to load item details. Please try again or contact support."
        />
        <div className="mt-4">
          <Button variant="primary" onClick={() => navigate('/inventory/items')}>
            Back to Items List
          </Button>
        </div>
      </div>
    );
  }
  
  return (
    <div>
      <PageHeader 
        title="Item Details" 
        subtitle={itemLoading ? 'Loading...' : item?.name}
        actionLabel="Edit Item"
        actionUrl={`/inventory/items/${id}/edit`}
      />
      
      {/* Item Basic Info Card */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        <Card className="lg:col-span-2">
          <CardHeader title="Basic Information" />
          <CardBody>
            {itemLoading ? (
              <div className="animate-pulse">
                <div className="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
                <div className="h-4 bg-gray-200 rounded w-1/2 mb-4"></div>
                <div className="h-4 bg-gray-200 rounded w-3/4 mb-4"></div>
                <div className="h-4 bg-gray-200 rounded w-full"></div>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Item Code</span>
                    <span className="block mt-1 text-base text-gray-900">{item?.item_code}</span>
                  </div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Name</span>
                    <span className="block mt-1 text-base text-gray-900">{item?.name}</span>
                  </div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Category</span>
                    <span className="block mt-1 text-base text-gray-900">
                      {item?.category ? (
                        <div className="flex items-center">
                          <Tag className="h-4 w-4 mr-1 text-gray-500" />
                          {item.category.name}
                        </div>
                      ) : (
                        'Not categorized'
                      )}
                    </span>
                  </div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Unit of Measure</span>
                    <span className="block mt-1 text-base text-gray-900">
                      {item?.unitOfMeasure ? (
                        <div className="flex items-center">
                          <Ruler className="h-4 w-4 mr-1 text-gray-500" />
                          {item.unitOfMeasure.name} ({item.unitOfMeasure.symbol})
                        </div>
                      ) : (
                        'Not specified'
                      )}
                    </span>
                  </div>
                </div>
                <div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Description</span>
                    <span className="block mt-1 text-base text-gray-900">
                      {item?.description || 'No description provided'}
                    </span>
                  </div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Created At</span>
                    <span className="block mt-1 text-base text-gray-900">
                      {item?.created_at ? new Date(item.created_at).toLocaleString() : '-'}
                    </span>
                  </div>
                  <div className="mb-4">
                    <span className="block text-sm font-medium text-gray-500">Updated At</span>
                    <span className="block mt-1 text-base text-gray-900">
                      {item?.updated_at ? new Date(item.updated_at).toLocaleString() : '-'}
                    </span>
                  </div>
                </div>
              </div>
            )}
          </CardBody>
        </Card>
        
        <Card>
          <CardHeader title="Stock Information" />
          <CardBody>
            {itemLoading ? (
              <div className="animate-pulse">
                <div className="h-4 bg-gray-200 rounded w-1/2 mb-4"></div>
                <div className="h-4 bg-gray-200 rounded w-3/4 mb-4"></div>
                <div className="h-4 bg-gray-200 rounded w-1/2"></div>
              </div>
            ) : (
              <div>
                <div className="mb-6 text-center">
                  <div className={`inline-flex items-center justify-center p-4 bg-${stockStatus.color}-100 rounded-full`}>
                    <stockStatus.icon className={`h-8 w-8 text-${stockStatus.color}-600`} />
                  </div>
                  <div className="mt-2">
                    <span className={`px-2 py-1 text-sm font-medium bg-${stockStatus.color}-100 text-${stockStatus.color}-800 rounded-full`}>
                      {stockStatus.text}
                    </span>
                  </div>
                </div>
                
                <div className="space-y-4">
                  <div className="flex justify-between items-center py-2 border-b border-gray-200">
                    <span className="text-gray-600">Current Stock:</span>
                    <span className="font-medium text-lg">{item?.current_stock || 0} {item?.unitOfMeasure?.symbol || ''}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-gray-200">
                    <span className="text-gray-600">Minimum Stock:</span>
                    <span>{item?.minimum_stock || 0} {item?.unitOfMeasure?.symbol || ''}</span>
                  </div>
                  <div className="flex justify-between items-center py-2 border-b border-gray-200">
                    <span className="text-gray-600">Maximum Stock:</span>
                    <span>{item?.maximum_stock || 0} {item?.unitOfMeasure?.symbol || ''}</span>
                  </div>
                </div>
                
                <div className="mt-6 space-y-2">
                  <Link 
                    to="/inventory/transactions/create" 
                    state={{ selectedItem: item }}
                    className="block"
                  >
                    <Button variant="primary" className="w-full">
                      <TrendingUp className="h-4 w-4 mr-2" />
                      Add Transaction
                    </Button>
                  </Link>
                  <Button 
                    variant="danger" 
                    className="w-full"
                    onClick={() => setDeleteModalOpen(true)}
                  >
                    <Trash className="h-4 w-4 mr-2" />
                    Delete Item
                  </Button>
                </div>
              </div>
            )}
          </CardBody>
        </Card>
      </div>
      
      {/* Item Transactions */}
      <Card>
        <CardHeader 
          title="Transaction History" 
          subtitle="Records of all stock movements for this item"
          action={
            <Link to="/inventory/transactions/create" state={{ selectedItem: item }}>
              <Button variant="primary" size="sm">
                <TrendingUp className="h-4 w-4 mr-2" />
                Add Transaction
              </Button>
            </Link>
          }
        />
        <CardBody>
          <Table
            columns={transactionColumns}
            data={transactions}
            isLoading={transactionsLoading}
            emptyMessage="No transactions found for this item."
          />
        </CardBody>
      </Card>
      
      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        title="Confirm Delete"
        size="sm"
        footer={
          <div className="flex justify-end space-x-3">
            <Button variant="light" onClick={() => setDeleteModalOpen(false)}>
              Cancel
            </Button>
            <Button 
              variant="danger" 
              onClick={handleDeleteItem}
              isLoading={deleteMutation.isLoading}
            >
              Delete Item
            </Button>
          </div>
        }
      >
        <p className="text-gray-700">
          Are you sure you want to delete this item? This action cannot be undone.
        </p>
        {item?.current_stock > 0 && (
          <div className="mt-4 p-3 bg-yellow-50 border-l-4 border-yellow-400 text-yellow-700">
            <div className="flex">
              <AlertTriangle className="h-5 w-5 mr-2" />
              <p>
                <strong>Warning:</strong> This item still has stock ({item.current_stock} {item.unitOfMeasure?.symbol || ''}). 
                Deleting it may cause inconsistencies in your inventory records.
              </p>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default ItemDetail;
