// frontend/erp/src/views/inventory/ItemsList.vue
<!-- src/views/inventory/ItemsList.vue -->
<template>
  <div class="items-list">
    <!-- Search and Filter Section -->
    <SearchFilter
      v-model:value="searchQuery"
      placeholder="Search items by code, name or description..."
      @search="applyFilters"
      @clear="clearSearch"
    >
      <template #filters>
        <div class="filter-group">
          <label for="categoryFilter">Category</label>
          <select id="categoryFilter" v-model="categoryFilter" @change="applyFilters">
            <option value="">All Categories</option>
            <option v-for="category in categories" :key="category.category_id" :value="category.category_id">
              {{ category.name }}
            </option>
          </select>
        </div>
        
        <div class="filter-group">
          <label for="stockStatusFilter">Stock Status</label>
          <select id="stockStatusFilter" v-model="stockStatusFilter" @change="applyFilters">
            <option value="">All Stock Status</option>
            <option value="low_stock">Low Stock</option>
            <option value="normal">Normal Stock</option>
            <option value="over_stock">Over Stock</option>
          </select>
        </div>
      </template>
      
      <template #actions>
        <button class="btn btn-primary" @click="openAddItemModal">
          <i class="fas fa-plus"></i> Add Item
        </button>
      </template>
    </SearchFilter>
    
    <!-- Items Table -->
    <div class="items-table-container">
      <div v-if="isLoading" class="loading-indicator">
        <i class="fas fa-spinner fa-spin"></i> Loading items...
      </div>
      
      <div v-else-if="filteredItems.length === 0" class="empty-state">
        <div class="empty-icon">
          <i class="fas fa-box-open"></i>
        </div>
        <h3>No items found</h3>
        <p>Try adjusting your search or filters, or add a new item.</p>
      </div>
      
      <table v-else class="data-table">
        <thead>
          <tr>
            <th @click="sortBy('item_code')" class="sortable">
              Item Code
              <i v-if="sortColumn === 'item_code'" :class="sortIconClass"></i>
            </th>
            <th @click="sortBy('name')" class="sortable">
              Name
              <i v-if="sortColumn === 'name'" :class="sortIconClass"></i>
            </th>
            <th>Category</th>
            <th>UOM</th>
            <th @click="sortBy('current_stock')" class="sortable">
              Current Stock
              <i v-if="sortColumn === 'current_stock'" :class="sortIconClass"></i>
            </th>
            <th>Min. Stock</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in paginatedItems" :key="item.item_id">
            <td>{{ item.item_code }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.category ? item.category.name : '-' }}</td>
            <td>{{ item.unitOfMeasure ? item.unitOfMeasure.symbol : '-' }}</td>
            <td>{{ item.current_stock }}</td>
            <td>{{ item.minimum_stock }}</td>
            <td>
              <span class="stock-status" :class="getStockStatusClass(item)">
                {{ getStockStatus(item) }}
              </span>
            </td>
            <td class="actions">
              <button class="action-btn" title="View Details" @click="viewItem(item)">
                <i class="fas fa-eye"></i>
              </button>
              <button class="action-btn" title="Edit Item" @click="editItem(item)">
                <i class="fas fa-edit"></i>
              </button>
              <button class="action-btn" title="Delete Item" @click="confirmDelete(item)">
                <i class="fas fa-trash"></i>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <!-- Pagination -->
    <Pagination
      v-if="filteredItems.length > 0"
      :current-page="currentPage"
      :total-pages="totalPages"
      :from="paginationInfo.from"
      :to="paginationInfo.to"
      :total="filteredItems.length"
      @page-changed="goToPage"
    />
    
    <!-- Add/Edit Item Modal -->
    <ItemFormModal
      v-if="showItemModal"
      :is-edit-mode="isEditMode"
      :item-form="itemForm"
      :categories="categories"
      :unit-of-measures="unitOfMeasures"
      @save="saveItem"
      @close="closeItemModal"
    />
    
    <!-- Delete Confirmation Modal -->
    <ConfirmationModal
      v-if="showDeleteModal"
      title="Confirm Delete"
      :message="`Are you sure you want to delete <strong>${itemToDelete.name}</strong>?`"
      confirm-button-text="Delete Item"
      confirm-button-class="btn-danger"
      @confirm="deleteItem"
      @close="closeDeleteModal"
    />
    
    <!-- Item Details Modal -->
    <ItemDetailModal
      v-if="showDetailModal"
      :item="selectedItem"
      @close="closeDetailModal"
    />
  </div>
</template>

<script>
import { ref, computed, onMounted, watch } from 'vue';
import api from '@/services/api';
import SearchFilter from '@/components/common/SearchFilter.vue';
import Pagination from '@/components/common/Pagination.vue';
import ItemFormModal from '@/components/inventory/ItemFormModal.vue';
import ItemDetailModal from '@/components/inventory/ItemDetailModal.vue';
import ConfirmationModal from '@/components/common/ConfirmationModal.vue';

export default {
  name: 'ItemsList',
  components: {
    SearchFilter,
    Pagination,
    ItemFormModal,
    ItemDetailModal,
    ConfirmationModal
  },
  setup() {
    const items = ref([]);
    const categories = ref([]);
    const unitOfMeasures = ref([]);
    const isLoading = ref(true);
    
    // Search and filtering
    const searchQuery = ref('');
    const categoryFilter = ref('');
    const stockStatusFilter = ref('');
    
    // Sorting
    const sortColumn = ref('item_code');
    const sortDirection = ref('asc');
    
    // Pagination
    const currentPage = ref(1);
    const itemsPerPage = ref(10);
    
    // Modals
    const showItemModal = ref(false);
    const showDeleteModal = ref(false);
    const showDetailModal = ref(false);
    const isEditMode = ref(false);
    const itemForm = ref({
      item_code: '',
      name: '',
      description: '',
      category_id: '',
      uom_id: '',
      minimum_stock: 0,
      maximum_stock: 0
    });
    const itemToDelete = ref({});
    const selectedItem = ref(null);
    
    // Computed properties
    const filteredItems = computed(() => {
      let result = [...items.value];
      
      // Apply search filter
      if (searchQuery.value) {
        const query = searchQuery.value.toLowerCase();
        result = result.filter(item => 
          (item.item_code && item.item_code.toLowerCase().includes(query)) || 
          (item.name && item.name.toLowerCase().includes(query)) ||
          (item.description && item.description.toLowerCase().includes(query))
        );
      }
      
      // Apply category filter
      if (categoryFilter.value) {
        result = result.filter(item => 
          item.category_id === parseInt(categoryFilter.value)
        );
      }
      
      // Apply stock status filter
      if (stockStatusFilter.value) {
        switch (stockStatusFilter.value) {
          case 'low_stock':
            result = result.filter(item => item.current_stock <= item.minimum_stock);
            break;
          case 'over_stock':
            result = result.filter(item => item.current_stock >= item.maximum_stock);
            break;
          case 'normal':
            result = result.filter(item => 
              item.current_stock > item.minimum_stock && 
              item.current_stock < item.maximum_stock
            );
            break;
        }
      }
      
      // Apply sorting
      result.sort((a, b) => {
        let comparison = 0;
        
        if (a[sortColumn.value] < b[sortColumn.value]) {
          comparison = -1;
        } else if (a[sortColumn.value] > b[sortColumn.value]) {
          comparison = 1;
        }
        
        return sortDirection.value === 'asc' ? comparison : -comparison;
      });
      
      return result;
    });
    
    // Pagination logic
    const totalPages = computed(() => {
      return Math.ceil(filteredItems.value.length / itemsPerPage.value);
    });
    
    const paginatedItems = computed(() => {
      const startIndex = (currentPage.value - 1) * itemsPerPage.value;
      const endIndex = startIndex + itemsPerPage.value;
      return filteredItems.value.slice(startIndex, endIndex);
    });
    
    const paginationInfo = computed(() => {
      const total = filteredItems.value.length;
      const from = total === 0 ? 0 : (currentPage.value - 1) * itemsPerPage.value + 1;
      const to = Math.min(currentPage.value * itemsPerPage.value, total);
      
      return { from, to, total };
    });
    
    const sortIconClass = computed(() => {
      return sortDirection.value === 'asc' ? 'fas fa-sort-up' : 'fas fa-sort-down';
    });
    
    // Methods
    const fetchItems = async () => {
      isLoading.value = true;
      
      try {
        const response = await api.get('/items');
        items.value = response.data.data;
      } catch (error) {
        console.error('Error fetching items:', error);
      } finally {
        isLoading.value = false;
      }
    };
    
    const fetchCategories = async () => {
      try {
        const response = await api.get('/item-categories');
        categories.value = response.data.data;
      } catch (error) {
        console.error('Error fetching categories:', error);
      }
    };
    
    const fetchUnitOfMeasures = async () => {
      try {
        const response = await api.get('/unit-of-measures');
        unitOfMeasures.value = response.data.data;
      } catch (error) {
        console.error('Error fetching unit of measures:', error);
      }
    };
    
    const getStockStatus = (item) => {
      if (item.current_stock <= item.minimum_stock) {
        return 'Low Stock';
      } else if (item.current_stock >= item.maximum_stock) {
        return 'Over Stock';
      } else {
        return 'Normal';
      }
    };
    
    const getStockStatusClass = (item) => {
      const status = getStockStatus(item);
      switch (status) {
        case 'Low Stock': return 'low';
        case 'Over Stock': return 'over';
        default: return 'normal';
      }
    };
    
    const applyFilters = () => {
      currentPage.value = 1;  // Reset to first page on filter change
    };
    
    const clearSearch = () => {
      searchQuery.value = '';
      applyFilters();
    };
    
    const sortBy = (column) => {
      if (sortColumn.value === column) {
        sortDirection.value = sortDirection.value === 'asc' ? 'desc' : 'asc';
      } else {
        sortColumn.value = column;
        sortDirection.value = 'asc';
      }
    };
    
    const goToPage = (page) => {
      currentPage.value = page;
    };
    
    const openAddItemModal = () => {
      isEditMode.value = false;
      itemForm.value = {
        item_code: '',
        name: '',
        description: '',
        category_id: '',
        uom_id: '',
        minimum_stock: 0,
        maximum_stock: 0
      };
      showItemModal.value = true;
    };
    
    const editItem = (item) => {
      isEditMode.value = true;
      itemForm.value = {
        item_id: item.item_id,
        item_code: item.item_code,
        name: item.name,
        description: item.description || '',
        category_id: item.category_id || '',
        uom_id: item.uom_id || '',
        minimum_stock: item.minimum_stock,
        maximum_stock: item.maximum_stock
      };
      showItemModal.value = true;
    };
    
    const viewItem = (item) => {
      selectedItem.value = item;
      showDetailModal.value = true;
    };
    
    const closeItemModal = () => {
      showItemModal.value = false;
    };
    
    const closeDetailModal = () => {
      showDetailModal.value = false;
      selectedItem.value = null;
    };
    
    const saveItem = async (formData) => {
      try {
        if (isEditMode.value) {
          await api.put(`/items/${formData.item_id}`, formData);
          
          // Update item in the list
          const index = items.value.findIndex(item => item.item_id === formData.item_id);
          if (index !== -1) {
            items.value[index] = { ...items.value[index], ...formData };
          }
          
          // Show success message
          alert('Item updated successfully!');
        } else {
          const response = await api.post('/items', formData);
          
          // Add new item to the list
          items.value.push(response.data.data);
          
          // Show success message
          alert('Item added successfully!');
        }
        
        // Close the modal
        closeItemModal();
      } catch (error) {
        console.error('Error saving item:', error);
        
        if (error.validationErrors) {
          alert('Please check the form for errors: ' + Object.values(error.validationErrors).join(', '));
        } else {
          alert('An error occurred while saving the item. Please try again.');
        }
      }
    };
    
    const confirmDelete = (item) => {
      itemToDelete.value = item;
      showDeleteModal.value = true;
    };
    
    const closeDeleteModal = () => {
      showDeleteModal.value = false;
    };
    
    const deleteItem = async () => {
      try {
        await api.delete(`/items/${itemToDelete.value.item_id}`);
        
        // Remove item from the list
        items.value = items.value.filter(item => item.item_id !== itemToDelete.value.item_id);
        
        // Close the modal
        closeDeleteModal();
        
        // Show success message
        alert('Item deleted successfully!');
      } catch (error) {
        console.error('Error deleting item:', error);
        
        if (error.response && error.response.status === 422) {
          alert('This item cannot be deleted because it has related transactions or batches.');
        } else {
          alert('An error occurred while deleting the item. Please try again.');
        }
      }
    };
    
    // Watch for changes that should reset pagination
    watch(filteredItems, (newItems, oldItems) => {
      if (Math.abs(newItems.length - oldItems.length) > itemsPerPage.value / 2) {
        currentPage.value = 1;
      }
    });
    
    // Initial data loading
    onMounted(() => {
      fetchItems();
      fetchCategories();
      fetchUnitOfMeasures();
    });
    
    return {
      items,
      categories,
      unitOfMeasures,
      isLoading,
      searchQuery,
      categoryFilter,
      stockStatusFilter,
      sortColumn,
      sortDirection,
      currentPage,
      itemsPerPage,
      filteredItems,
      paginatedItems,
      totalPages,
      paginationInfo,
      showItemModal,
      showDeleteModal,
      showDetailModal,
      isEditMode,
      itemForm,
      itemToDelete,
      selectedItem,
      sortIconClass,
      getStockStatus,
      getStockStatusClass,
      applyFilters,
      clearSearch,
      sortBy,
      goToPage,
      openAddItemModal,
      editItem,
      viewItem,
      closeItemModal,
      closeDetailModal,
      saveItem,
      confirmDelete,
      closeDeleteModal,
      deleteItem
    };
  }
};
</script>

<style scoped>
.items-list {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.items-table-container {
  background-color: white;
  border-radius: 0.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}

.data-table th {
  text-align: left;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #e2e8f0;
  background-color: #f8fafc;
  font-weight: 500;
  color: #64748b;
}

.data-table td {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid #f1f5f9;
  color: #1e293b;
}

.data-table tr:hover td {
  background-color: #f8fafc;
}

.sortable {
  cursor: pointer;
  position: relative;
}

.sortable i {
  margin-left: 0.5rem;
  font-size: 0.75rem;
}

.stock-status {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.75rem;
  font-weight: 500;
}

.stock-status.low {
  background-color: #fee2e2;
  color: #dc2626;
}

.stock-status.normal {
  background-color: #d1fae5;
  color: #059669;
}

.stock-status.over {
  background-color: #fef3c7;
  color: #d97706;
}

.actions {
  display: flex;
  gap: 0.5rem;
  justify-content: flex-end;
}

.action-btn {
  background: none;
  border: none;
  color: #64748b;
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 0.25rem;
  transition: background-color 0.2s, color 0.2s;
}

.action-btn:hover {
  background-color: #f1f5f9;
  color: #0f172a;
}

.loading-indicator {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 4rem 0;
  color: #64748b;
  font-size: 1rem;
}

.loading-indicator i {
  margin-right: 0.5rem;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 4rem 0;
  text-align: center;
  color: #64748b;
}

.empty-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
  color: #cbd5e1;
}

.empty-state h3 {
  font-size: 1.25rem;
  margin: 0 0 0.5rem 0;
  color: #1e293b;
}

.empty-state p {
  margin: 0;
  font-size: 0.875rem;
}

@media (max-width: 768px) {
  .data-table {
    font-size: 0.75rem;
  }
  
  .data-table th,
  .data-table td {
    padding: 0.5rem;
  }
  
  .actions {
    flex-direction: column;
    gap: 0.25rem;
  }
}
</style>

// frontend/src/pages/inventory/items/ItemsList.jsx
// src/pages/inventory/items/ItemsList.jsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useQuery } from 'react-query';
import { Search, Filter, Plus, Trash, Edit, Eye } from 'lucide-react';
import { itemService, categoryService } from '../../../services/inventoryService';
import PageHeader from '../../../components/common/PageHeader';
import Table from '../../../components/common/Table';
import { Card, CardBody } from '../../../components/common/Card';
import { 
  FormGroup, 
  Label, 
  Input, 
  Select, 
  Button 
} from '../../../components/common/FormElements';
import Alert from '../../../components/common/Alert';
import Modal from '../../../components/common/Modal';

const ItemsList = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const queryParams = new URLSearchParams(location.search);
  
  // State for filters
  const [filters, setFilters] = useState({
    search: queryParams.get('search') || '',
    category: queryParams.get('category') || '',
    status: queryParams.get('status') || '',
  });
  
  // State for pagination
  const [pagination, setPagination] = useState({
    page: parseInt(queryParams.get('page') || '1', 10),
    perPage: parseInt(queryParams.get('perPage') || '10', 10),
  });
  
  // State for delete modal
  const [deleteModalOpen, setDeleteModalOpen] = useState(false);
  const [itemToDelete, setItemToDelete] = useState(null);
  
  // Update URL with filters and pagination
  useEffect(() => {
    const params = new URLSearchParams();
    if (filters.search) params.append('search', filters.search);
    if (filters.category) params.append('category', filters.category);
    if (filters.status) params.append('status', filters.status);
    params.append('page', pagination.page.toString());
    params.append('perPage', pagination.perPage.toString());
    
    navigate({
      pathname: location.pathname,
      search: params.toString(),
    }, { replace: true });
  }, [filters, pagination, navigate, location.pathname]);
  
  // Fetch items with filters and pagination
  const { 
    data: itemsData, 
    isLoading: itemsLoading, 
    isError: itemsError,
    refetch: refetchItems
  } = useQuery(
    ['items', filters, pagination],
    () => itemService.getAll({
      search: filters.search,
      category_id: filters.category,
      status: filters.status,
      page: pagination.page,
      per_page: pagination.perPage,
    }),
    {
      keepPreviousData: true,
    }
  );
  
  // Fetch categories for filter dropdown
  const { 
    data: categoriesData, 
    isLoading: categoriesLoading 
  } = useQuery(
    'categories',
    () => categoryService.getAll()
  );
  
  // Handle filter changes
  const handleFilterChange = (name, value) => {
    setFilters((prev) => ({
      ...prev,
      [name]: value,
    }));
    // Reset to first page when filters change
    setPagination((prev) => ({
      ...prev,
      page: 1,
    }));
  };
  
  // Handle page change
  const handlePageChange = (newPage) => {
    setPagination((prev) => ({
      ...prev,
      page: newPage,
    }));
  };
  
  // Handle per page change
  const handlePerPageChange = (e) => {
    const newPerPage = parseInt(e.target.value, 10);
    setPagination({
      page: 1, // Reset to first page
      perPage: newPerPage,
    });
  };
  
  // Handle reset filters
  const handleResetFilters = () => {
    setFilters({
      search: '',
      category: '',
      status: '',
    });
    setPagination({
      page: 1,
      perPage: 10,
    });
  };
  
  // Handle delete item
  const handleDeleteItem = async () => {
    if (!itemToDelete) return;
    
    try {
      await itemService.delete(itemToDelete.item_id);
      setDeleteModalOpen(false);
      setItemToDelete(null);
      refetchItems();
    } catch (error) {
      console.error('Error deleting item:', error);
      // Handle error, maybe show a notification
    }
  };
  
  // Table columns definition
  const columns = [
    {
      key: 'item_code',
      label: 'Item Code',
      render: (item) => (
        <div className="font-medium text-gray-900">{item.item_code}</div>
      ),
    },
    {
      key: 'name',
      label: 'Name',
      render: (item) => (
        <Link to={`/inventory/items/${item.item_id}`} className="text-indigo-600 hover:text-indigo-900">
          {item.name}
        </Link>
      ),
    },
    {
      key: 'category',
      label: 'Category',
      render: (item) => (
        <div>{item.category?.name || '-'}</div>
      ),
    },
    {
      key: 'uom',
      label: 'UOM',
      render: (item) => (
        <div>{item.unitOfMeasure?.symbol || '-'}</div>
      ),
    },
    {
      key: 'current_stock',
      label: 'Current Stock',
      render: (item) => (
        <div>{item.current_stock}</div>
      ),
    },
    {
      key: 'status',
      label: 'Status',
      render: (item) => {
        let statusClass = 'bg-green-100 text-green-800'; // Normal
        if (item.status === 'Low Stock') {
          statusClass = 'bg-red-100 text-red-800';
        } else if (item.status === 'Over Stock') {
          statusClass = 'bg-yellow-100 text-yellow-800';
        }
        
        return (
          <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${statusClass}`}>
            {item.status}
          </span>
        );
      },
    },
    {
      key: 'actions',
      label: 'Actions',
      render: (item) => (
        <div className="flex space-x-2">
          <Link 
            to={`/inventory/items/${item.item_id}`}
            className="text-blue-600 hover:text-blue-900"
            title="View"
          >
            <Eye className="h-5 w-5" />
          </Link>
          <Link 
            to={`/inventory/items/${item.item_id}/edit`}
            className="text-indigo-600 hover:text-indigo-900"
            title="Edit"
          >
            <Edit className="h-5 w-5" />
          </Link>
          <button 
            onClick={() => {
              setItemToDelete(item);
              setDeleteModalOpen(true);
            }}
            className="text-red-600 hover:text-red-900"
            title="Delete"
          >
            <Trash className="h-5 w-5" />
          </button>
        </div>
      ),
    },
  ];

  return (
    <div>
      <PageHeader 
        title="Items" 
        subtitle="Manage your inventory items"
        actionLabel="Add New Item"
        actionUrl="/inventory/items/create"
      />
      
      {/* Filters */}
      <Card className="mb-6">
        <CardBody>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <FormGroup>
              <Label htmlFor="search">Search</Label>
              <div className="relative rounded-md shadow-sm">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Search className="h-5 w-5 text-gray-400" />
                </div>
                <Input
                  id="search"
                  value={filters.search}
                  onChange={(e) => handleFilterChange('search', e.target.value)}
                  placeholder="Search by code or name"
                  className="pl-10"
                />
              </div>
            </FormGroup>
            
            <FormGroup>
              <Label htmlFor="category">Category</Label>
              <Select
                id="category"
                value={filters.category}
                onChange={(e) => handleFilterChange('category', e.target.value)}
                options={
                  categoriesLoading
                    ? []
                    : categoriesData?.data.map((category) => ({
                        value: category.category_id,
                        label: category.name,
                      })) || []
                }
                placeholder="All Categories"
                disabled={categoriesLoading}
              />
            </FormGroup>
            
            <FormGroup>
              <Label htmlFor="status">Status</Label>
              <Select
                id="status"
                value={filters.status}
                onChange={(e) => handleFilterChange('status', e.target.value)}
                options={[
                  { value: 'Low Stock', label: 'Low Stock' },
                  { value: 'Normal', label: 'Normal' },
                  { value: 'Over Stock', label: 'Over Stock' },
                ]}
                placeholder="All Status"
              />
            </FormGroup>
            
            <div className="flex items-end">
              <Button
                variant="secondary"
                onClick={handleResetFilters}
                className="w-full"
              >
                <Filter className="h-4 w-4 mr-2" />
                Reset Filters
              </Button>
            </div>
          </div>
        </CardBody>
      </Card>
      
      {/* Items Table */}
      {itemsError && (
        <Alert
          type="error"
          title="Error loading items"
          message="There was an error loading the items. Please try again later."
          className="mb-6"
        />
      )}
      
      <Table
        columns={columns}
        data={itemsData?.data || []}
        isLoading={itemsLoading}
        pagination={itemsData?.meta}
        onPageChange={handlePageChange}
        emptyMessage="No items found matching your filters."
      />
      
      {/* Items per page selector */}
      <div className="mt-4 flex justify-end items-center">
        <span className="mr-2 text-sm text-gray-600">Items per page:</span>
        <select
          value={pagination.perPage}
          onChange={handlePerPageChange}
          className="form-select border border-gray-300 rounded-md shadow-sm text-sm"
        >
          <option value="10">10</option>
          <option value="25">25</option>
          <option value="50">50</option>
          <option value="100">100</option>
        </select>
      </div>
      
      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        title="Confirm Delete"
        size="sm"
        footer={
          <div className="flex justify-end space-x-3">
            <Button variant="light" onClick={() => setDeleteModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="danger" onClick={handleDeleteItem}>
              Delete
            </Button>
          </div>
        }
      >
        <p className="text-gray-700">
          Are you sure you want to delete the item "{itemToDelete?.name}"? This action cannot be undone.
        </p>
      </Modal>
    </div>
  );
};

export default ItemsList;
