// frontend/erp/src/views/inventory/ItemDetail.vue
<!-- src/views/inventory/ItemDetail.vue -->
<template>
  <div class="item-detail-view">
    <div class="page-header">
      <div class="header-left">
        <button class="back-button" @click="$router.back()">
          <i class="fas fa-arrow-left"></i> Back
        </button>
        <h1 class="page-title">Item Details</h1>
      </div>
      
      <div class="header-actions">
        <button class="btn btn-secondary" @click="openEditModal">
          <i class="fas fa-edit"></i> Edit
        </button>
        <button class="btn btn-danger" @click="confirmDelete" v-if="canDelete">
          <i class="fas fa-trash"></i> Delete
        </button>
      </div>
    </div>

    <div v-if="isLoading" class="loading-indicator">
      <i class="fas fa-spinner fa-spin"></i> Loading item details...
    </div>

    <div v-else-if="!item" class="error-message">
      <div class="error-icon">
        <i class="fas fa-exclamation-circle"></i>
      </div>
      <h2>Item Not Found</h2>
      <p>The requested item could not be found.</p>
      <button class="btn btn-primary" @click="$router.push('/items')">
        Back to Items List
      </button>
    </div>

    <div v-else class="item-detail-container">
      <!-- Basic Info Card -->
      <div class="detail-card">
        <div class="card-header">
          <h2 class="card-title">Basic Information</h2>
        </div>
        <div class="card-body">
          <div class="detail-grid">
            <div class="detail-row">
              <div class="detail-label">Item Code</div>
              <div class="detail-value">{{ item.item_code }}</div>
            </div>
            <div class="detail-row">
              <div class="detail-label">Name</div>
              <div class="detail-value">{{ item.name }}</div>
            </div>
            <div class="detail-row">
              <div class="detail-label">Category</div>
              <div class="detail-value">{{ item.category ? item.category.name : '-' }}</div>
            </div>
            <div class="detail-row">
              <div class="detail-label">Unit of Measure</div>
              <div class="detail-value">
                {{ item.unitOfMeasure ? `${item.unitOfMeasure.name} (${item.unitOfMeasure.symbol})` : '-' }}
              </div>
            </div>
            <div class="detail-row" v-if="item.description">
              <div class="detail-label">Description</div>
              <div class="detail-value description">{{ item.description }}</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Stock Info Card -->
      <div class="detail-card">
        <div class="card-header">
          <h2 class="card-title">Stock Information</h2>
        </div>
        <div class="card-body">
          <div class="stock-summary">
            <div class="stock-stat">
              <div class="stat-label">Current Stock</div>
              <div class="stat-value">{{ item.current_stock }}</div>
              <div class="stat-unit">{{ item.unitOfMeasure?.symbol || '' }}</div>
            </div>
            <div class="stock-stat">
              <div class="stat-label">Minimum Stock</div>
              <div class="stat-value">{{ item.minimum_stock }}</div>
              <div class="stat-unit">{{ item.unitOfMeasure?.symbol || '' }}</div>
            </div>
            <div class="stock-stat">
              <div class="stat-label">Maximum Stock</div>
              <div class="stat-value">{{ item.maximum_stock }}</div>
              <div class="stat-unit">{{ item.unitOfMeasure?.symbol || '' }}</div>
            </div>
            <div class="stock-stat">
              <div class="stat-label">Status</div>
              <div class="stat-value status">
                <span class="stock-status" :class="getStockStatusClass(item)">
                  {{ getStockStatus(item) }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Batches Card -->
      <div class="detail-card" v-if="item.batches && item.batches.length > 0">
        <div class="card-header">
          <h2 class="card-title">Batches</h2>
        </div>
        <div class="card-body">
          <div class="card-table">
            <table>
              <thead>
                <tr>
                  <th>Batch Number</th>
                  <th>Expiry Date</th>
                  <th>Manufacturing Date</th>
                  <th>Lot Number</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="batch in item.batches" :key="batch.batch_id">
                  <td>{{ batch.batch_number }}</td>
                  <td>{{ formatDate(batch.expiry_date) }}</td>
                  <td>{{ formatDate(batch.manufacturing_date) }}</td>
                  <td>{{ batch.lot_number || '-' }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Transactions Card -->
      <div class="detail-card">
        <div class="card-header">
          <h2 class="card-title">Recent Transactions</h2>
          <router-link :to="`/stock-transactions?item_id=${item.item_id}`" class="card-action">
            View All
          </router-link>
        </div>
        <div class="card-body">
          <div v-if="isLoadingTransactions" class="loading-indicator">
            <i class="fas fa-spinner fa-spin"></i> Loading transactions...
          </div>
          <div v-else-if="transactions.length === 0" class="empty-state">
            <p>No transactions found for this item.</p>
          </div>
          <div v-else class="card-table">
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Type</th>
                  <th>Quantity</th>
                  <th>Warehouse</th>
                  <th>Reference</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="transaction in transactions" :key="transaction.transaction_id">
                  <td>{{ formatDate(transaction.transaction_date) }}</td>
                  <td>
                    <span class="transaction-type" :class="getTransactionTypeClass(transaction.transaction_type)">
                      {{ transaction.transaction_type }}
                    </span>
                  </td>
                  <td :class="getQuantityClass(transaction.transaction_type)">
                    {{ transaction.quantity }} {{ item.unitOfMeasure?.symbol || '' }}
                  </td>
                  <td>{{ transaction.warehouse?.name || '-' }}</td>
                  <td>{{ transaction.reference_document || '-' }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Item Form Modal -->
    <ItemFormModal
      v-if="showEditModal"
      :is-edit-mode="true"
      :item-form="itemForm"
      :categories="categories"
      :unit-of-measures="unitOfMeasures"
      @save="saveItem"
      @close="closeEditModal"
    />

    <!-- Delete Confirmation Modal -->
    <ConfirmationModal
      v-if="showDeleteModal"
      title="Confirm Delete"
      :message="`Are you sure you want to delete <strong>${item?.name}</strong>?`"
      confirm-button-text="Delete Item"
      confirm-button-class="btn btn-danger"
      @confirm="deleteItem"
      @close="closeDeleteModal"
    />
  </div>
</template>

<script>
import { ref, reactive, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import ItemService from '@/services/ItemService.js';
import ItemFormModal from '@/components/inventory/ItemFormModal.vue';
import ConfirmationModal from '@/components/common/ConfirmationModal.vue';

export default {
  name: 'ItemDetail',
  components: {
    ItemFormModal,
    ConfirmationModal
  },
  props: {
    id: {
      type: [String, Number],
      required: true
    }
  },
  setup(props) {
    const router = useRouter();
    const item = ref(null);
    const transactions = ref([]);
    const categories = ref([]);
    const unitOfMeasures = ref([]);
    const isLoading = ref(true);
    const isLoadingTransactions = ref(true);
    const showEditModal = ref(false);
    const showDeleteModal = ref(false);
    const itemForm = reactive({
      item_id: null,
      item_code: '',
      name: '',
      description: '',
      category_id: '',
      uom_id: '',
      minimum_stock: 0,
      maximum_stock: 0
    });

    const canDelete = computed(() => {
      if (!item.value) return false;
      
      // Check if item has transactions or batches
      const hasTransactions = transactions.value.length > 0;
      const hasBatches = item.value.batches && item.value.batches.length > 0;
      
      return !hasTransactions && !hasBatches;
    });

    const fetchItem = async () => {
      isLoading.value = true;
      try {
        const response = await ItemService.getItemById(props.id);
        item.value = response.data;
        
        // Populate form for potential edit
        Object.assign(itemForm, {
          item_id: item.value.item_id,
          item_code: item.value.item_code,
          name: item.value.name,
          description: item.value.description || '',
          category_id: item.value.category_id || '',
          uom_id: item.value.uom_id || '',
          minimum_stock: item.value.minimum_stock,
          maximum_stock: item.value.maximum_stock
        });
      } catch (error) {
        console.error('Error fetching item:', error);
        item.value = null;
      } finally {
        isLoading.value = false;
      }
    };

    const fetchTransactions = async () => {
      if (!props.id) return;
      
      isLoadingTransactions.value = true;
      try {
        const response = await ItemService.getItemTransactions(props.id, { limit: 10 });
        transactions.value = response.data || [];
      } catch (error) {
        console.error('Error fetching transactions:', error);
        transactions.value = [];
      } finally {
        isLoadingTransactions.value = false;
      }
    };

    const fetchCategories = async () => {
      try {
        const response = await ItemService.getCategories();
        categories.value = response.data || [];
      } catch (error) {
        console.error('Error fetching categories:', error);
        categories.value = [];
      }
    };

    const fetchUnitOfMeasures = async () => {
      try {
        const response = await ItemService.getUnitsOfMeasure();
        unitOfMeasures.value = response.data || [];
      } catch (error) {
        console.error('Error fetching units of measure:', error);
        unitOfMeasures.value = [];
      }
    };

    const formatDate = (dateString) => {
      if (!dateString) return '-';
      const date = new Date(dateString);
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      });
    };

    const getStockStatus = (item) => {
      if (item.current_stock <= item.minimum_stock) {
        return 'Low Stock';
      } else if (item.current_stock >= item.maximum_stock) {
        return 'Over Stock';
      } else {
        return 'Normal';
      }
    };

    const getStockStatusClass = (item) => {
      const status = getStockStatus(item);
      switch (status) {
        case 'Low Stock': return 'low';
        case 'Over Stock': return 'over';
        default: return 'normal';
      }
    };

    const getTransactionTypeClass = (type) => {
      if (['IN', 'RECEIPT', 'RETURN', 'ADJUSTMENT_IN'].includes(type)) {
        return 'type-in';
      } else if (['OUT', 'ISSUE', 'SALE', 'ADJUSTMENT_OUT'].includes(type)) {
        return 'type-out';
      }
      return '';
    };

    const getQuantityClass = (type) => {
      if (['IN', 'RECEIPT', 'RETURN', 'ADJUSTMENT_IN'].includes(type)) {
        return 'quantity-in';
      } else if (['OUT', 'ISSUE', 'SALE', 'ADJUSTMENT_OUT'].includes(type)) {
        return 'quantity-out';
      }
      return '';
    };

    const openEditModal = () => {
      showEditModal.value = true;
    };

    const closeEditModal = () => {
      showEditModal.value = false;
    };

    const saveItem = async (formData) => {
      try {
        await ItemService.updateItem(formData.item_id, formData);
        
        // Refresh item data
        await fetchItem();
        
        // Close modal
        closeEditModal();
        
        // Show success message
        alert('Item updated successfully!');
      } catch (error) {
        console.error('Error updating item:', error);
        
        if (error.validationErrors) {
          alert('Please check the form for errors: ' + Object.values(error.validationErrors).join(', '));
        } else {
          alert('An error occurred while updating the item. Please try again.');
        }
      }
    };

    const confirmDelete = () => {
      showDeleteModal.value = true;
    };

    const closeDeleteModal = () => {
      showDeleteModal.value = false;
    };

    const deleteItem = async () => {
      try {
        await ItemService.deleteItem(props.id);
        
        // Close modal
        closeDeleteModal();
        
        // Show success message
        alert('Item deleted successfully!');
        
        // Navigate back to items list
        router.push('/items');
      } catch (error) {
        console.error('Error deleting item:', error);
        
        if (error.response && error.response.status === 422) {
          alert('This item cannot be deleted because it has related transactions or batches.');
        } else {
          alert('An error occurred while deleting the item. Please try again.');
        }
      }
    };

    onMounted(() => {
      fetchItem();
      fetchTransactions();
      fetchCategories();
      fetchUnitOfMeasures();
    });

    return {
      item,
      transactions,
      categories,
      unitOfMeasures,
      isLoading,
      isLoadingTransactions,
      showEditModal,
      showDeleteModal,
      itemForm,
      canDelete,
      formatDate,
      getStockStatus,
      getStockStatusClass,
      getTransactionTypeClass,
      getQuantityClass,
      openEditModal,
      closeEditModal,
      saveItem,
      confirmDelete,
      closeDeleteModal,
      deleteItem
    };
  }
};
</script>

<style scoped>
.item-detail-view {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.back-button {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  color: #64748b;
  background: none;
  border: none;
  padding: 0.5rem;
  cursor: pointer;
  font-size: 0.875rem;
  transition: color 0.2s;
}

.back-button:hover {
  color: #1e293b;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 600;
  margin: 0;
  color: #1e293b;
}

.header-actions {
  display: flex;
  gap: 0.75rem;
}

.item-detail-container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 1.5rem;
}

.detail-card {
  background-color: white;
  border-radius: 0.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 1.5rem;
  background-color: #f8fafc;
  border-bottom: 1px solid #e2e8f0;
}

.card-title {
  font-size: 1.125rem;
  font-weight: 600;
  margin: 0;
  color: #1e293b;
}

.card-action {
  font-size: 0.875rem;
  color: #2563eb;
  text-decoration: none;
}

.card-action:hover {
  text-decoration: underline;
}

.card-body {
  padding: 1.5rem;
}

.detail-grid {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.detail-row {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.detail-label {
  font-size: 0.75rem;
  color: #64748b;
  font-weight: 500;
}

.detail-value {
  color: #1e293b;
  font-size: 0.875rem;
}

.detail-value.description {
  white-space: pre-line;
  line-height: 1.5;
}

.stock-summary {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  gap: 1rem;
}

.stock-stat {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  padding: 1rem;
  border-radius: 0.375rem;
  background-color: #f8fafc;
}

.stat-label {
  font-size: 0.75rem;
  color: #64748b;
  margin-bottom: 0.5rem;
}

.stat-value {
  font-size: 1.5rem;
  font-weight: 600;
  color: #1e293b;
}

.stat-unit {
  font-size: 0.75rem;
  color: #64748b;
  margin-top: 0.25rem;
}

.stat-value.status {
  font-size: 1rem;
}

.stock-status {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.75rem;
  font-weight: 500;
}

.stock-status.low {
  background-color: #fee2e2;
  color: #dc2626;
}

.stock-status.normal {
  background-color: #d1fae5;
  color: #059669;
}

.stock-status.over {
  background-color: #fef3c7;
  color: #d97706;
}

.card-table {
  overflow-x: auto;
}

.card-table table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}

.card-table th {
  text-align: left;
  padding: 0.75rem 0.5rem;
  border-bottom: 1px solid #e2e8f0;
  font-weight: 500;
  color: #64748b;
}

.card-table td {
  padding: 0.75rem 0.5rem;
  border-bottom: 1px solid #f1f5f9;
  color: #1e293b;
}

.transaction-type {
  display: inline-block;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.75rem;
  font-weight: 500;
}

.type-in {
  background-color: #d1fae5;
  color: #059669;
}

.type-out {
  background-color: #fee2e2;
  color: #dc2626;
}

.quantity-in {
  color: #059669;
}

.quantity-out {
  color: #dc2626;
}

.empty-state {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 2rem 0;
  color: #64748b;
  font-style: italic;
}

.loading-indicator {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 2rem 0;
  color: #64748b;
}

.loading-indicator i {
  margin-right: 0.5rem;
}

.error-message {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 4rem 0;
}

.error-icon {
  font-size: 3rem;
  color: #f43f5e;
  margin-bottom: 1rem;
}

.error-message h2 {
  margin: 0 0 0.5rem 0;
  color: #1e293b;
}

.error-message p {
  margin: 0 0 1.5rem 0;
  color: #64748b;
}

@media (max-width: 768px) {
  .item-detail-container {
    grid-template-columns: 1fr;
  }
  
  .page-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }
  
  .header-actions {
    align-self: flex-end;
  }
  
  .stock-summary {
    grid-template-columns: repeat(2, 1fr);
  }
}
</style>

// frontend/src/pages/Items/ItemDetail.jsx
// src/pages/Items/ItemDetail.jsx
import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { itemService, stockTransactionService } from '../../services/inventoryService';

const ItemDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [item, setItem] = useState(null);
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  useEffect(() => {
    const fetchData = async () => {
      try {
        const [itemRes, transactionsRes] = await Promise.all([
          itemService.getById(id),
          stockTransactionService.getItemTransactions(id)
        ]);
        
        setItem(itemRes.data.data);
        setTransactions(transactionsRes.data.data);
      } catch (err) {
        setError('Error loading item details');
        console.error('Error fetching item details:', err);
      } finally {
        setLoading(false);
      }
    };
    
    fetchData();
  }, [id]);
  
  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <p>Loading item details...</p>
      </div>
    );
  }
  
  if (error || !item) {
    return (
      <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
        {error || 'Item not found'}
      </div>
    );
  }
  
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">Item Details</h1>
        <div className="space-x-2">
          <Link to={`/items/${id}/edit`} className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md">
            Edit Item
          </Link>
          <Link to="/stock-transactions/create" className="bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-md">
            Add Transaction
          </Link>
        </div>
      </div>
      
      {/* Item Details Card */}
      <div className="bg-white shadow-md rounded-md overflow-hidden">
        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h2 className="text-xl font-semibold mb-4">Basic Information</h2>
              <table className="min-w-full">
                <tbody>
                  <tr>
                    <td className="py-2 font-medium">Item Code:</td>
                    <td className="py-2">{item.item_code}</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">Name:</td>
                    <td className="py-2">{item.name}</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">Category:</td>
                    <td className="py-2">{item.category?.name || '-'}</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">UOM:</td>
                    <td className="py-2">{item.unitOfMeasure?.name || '-'} ({item.unitOfMeasure?.symbol || '-'})</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">Description:</td>
                    <td className="py-2">{item.description || '-'}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            
            <div>
              <h2 className="text-xl font-semibold mb-4">Stock Information</h2>
              <table className="min-w-full">
                <tbody>
                  <tr>
                    <td className="py-2 font-medium">Current Stock:</td>
                    <td className="py-2 font-bold">{item.current_stock} {item.unitOfMeasure?.symbol || ''}</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">Minimum Stock:</td>
                    <td className="py-2">{item.minimum_stock} {item.unitOfMeasure?.symbol || ''}</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">Maximum Stock:</td>
                    <td className="py-2">{item.maximum_stock} {item.unitOfMeasure?.symbol || ''}</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-medium">Status:</td>
                    <td className="py-2">
                      <span 
                        className={`px-2 py-1 rounded-full text-xs font-medium
                          ${item.current_stock <= item.minimum_stock ? 'bg-red-100 text-red-800' : 
                            item.current_stock >= item.maximum_stock ? 'bg-yellow-100 text-yellow-800' : 
                            'bg-green-100 text-green-800'}`}
                      >
                        {item.current_stock <= item.minimum_stock ? 'Low Stock' : 
                         item.current_stock >= item.maximum_stock ? 'Over Stock' : 'Normal'}
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      
      {/* Item Batches */}
      {item.batches && item.batches.length > 0 && (
        <div className="bg-white shadow-md rounded-md overflow-hidden">
          <div className="p-6">
            <h2 className="text-xl font-semibold mb-4">Batches</h2>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Batch Number</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Expiry Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Manufacturing Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Lot Number</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {item.batches.map(batch => (
                    <tr key={batch.batch_id}>
                      <td className="px-6 py-4 whitespace-nowrap">{batch.batch_number}</td>
                      <td className="px-6 py-4 whitespace-nowrap">{batch.expiry_date || '-'}</td>
                      <td className="px-6 py-4 whitespace-nowrap">{batch.manufacturing_date || '-'}</td>
                      <td className="px-6 py-4 whitespace-nowrap">{batch.lot_number || '-'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
      
      {/* Transaction History */}
      <div className="bg-white shadow-md rounded-md overflow-hidden">
        <div className="p-6">
          <h2 className="text-xl font-semibold mb-4">Transaction History</h2>
          
          {transactions.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Warehouse</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reference</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {transactions.map(transaction => (
                    <tr key={transaction.transaction_id}>
                      <td className="px-6 py-4 whitespace-nowrap">{new Date(transaction.transaction_date).toLocaleDateString()}</td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span 
                          className={`px-2 py-1 rounded-full text-xs font-medium
                            ${transaction.transaction_type.includes('IN') || transaction.transaction_type.includes('RECEIPT') ? 
                              'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}
                        >
                          {transaction.transaction_type}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {transaction.quantity} {item.unitOfMeasure?.symbol || ''}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">{transaction.warehouse?.name || '-'}</td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {transaction.reference_document ? 
                          `${transaction.reference_document} ${transaction.reference_number || ''}` : '-'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="text-gray-500">No transactions found for this item.</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default ItemDetail;
